### ISSUE TITLE
Valenting the dev use tagged versions of models

### ISSUE THREAD

**Issue by MichaelBitard** [pbstck/models#6]
### Why
It is painful to update rust deps and go deps pointing to master directly.
Maybe we want to have some more strict versionning?

Related to https://github.com/pbstck/intake/pull/258

### Demo

* when pushing on master on the models repository, there is a semver tag pushed along the commit (we always bump minor when a new tag is delivered)
* in the following repository use tagged versions of models
  * intake (intake-server + mithrandir)
  * aggregation-processings (agg + darty)

**Comment by cforycki** [comment]
TODO: use tagged version of models in aggregation-processings
